### Create a new auction
POST http://localhost:8080/api/v1/auctions
Content-Type: application/json

{
  "title": "Vintage Watch",
  "startingBid": 10.00,
  "maxBid": 1000.00,
  "startTime": "2026-01-01T10:00:00Z",
  "endTime": "2026-01-07T10:00:00Z"
}

### Get auction by ID
GET http://localhost:8080/api/v1/auctions/33446b0e-220b-4082-946a-616fa5eec996


### Post a bid to an auction
POST http://localhost:8080/api/v1/bids
Content-Type: application/json

{
  "auctionId": "acf5eb68-5520-4325-b146-fad03645961a",
  "bidUserId": "550e8400-e29b-41d4-a716-446655440002",
  "bidPrice": 200.00
}

### Get score board for an auction
GET http://localhost:8080/api/v1/bids/acf5eb68-5520-4325-b146-fad03645961a/score-board
