spring:
  application:
    name: auction-house
  datasource:
    url: jdbc:postgresql://localhost:5432/auctiondb
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000ms
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: auction-house-group